/**
 * Asset manifest for cache-busted file references
 *
 * Reads manifest.json generated by build scripts to provide
 * hashed filenames for CSS/JS files in templates.
 *
 * Usage in templates:
 *   <link rel="stylesheet" href="{{ assets.css }}">
 *   <script src="{{ assets.js }}"></script>
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const manifestPath = path.join(__dirname, 'manifest.json');

export default function() {
  // If manifest doesn't exist yet (first build), return defaults
  if (!fs.existsSync(manifestPath)) {
    return {
      css: '/css/main.css',
      js: '/js/main.js'
    };
  }

  // Read manifest and return asset paths
  try {
    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

    return {
      css: manifest['main.css'] || '/css/main.css',
      js: manifest['main.js'] || '/js/main.js'
    };
  } catch (error) {
    console.error('Error reading asset manifest:', error);
    // Fallback to defaults on error
    return {
      css: '/css/main.css',
      js: '/js/main.js'
    };
  }
}
